// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOCP0kZJRLsN_r5ZVDW6kP8T5xV8ZEX80',
    appId: '1:191712225769:web:65f9374d75231721518378',
    messagingSenderId: '191712225769',
    projectId: 'fooddelivery-8eb93',
    authDomain: 'fooddelivery-8eb93.firebaseapp.com',
    storageBucket: 'fooddelivery-8eb93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe5Q5BQ6AMfpBydHyVCBIR7YmknEwpqFE',
    appId: '1:191712225769:android:d1e8734782aa95de518378',
    messagingSenderId: '191712225769',
    projectId: 'fooddelivery-8eb93',
    storageBucket: 'fooddelivery-8eb93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQBUZbwVO-CVa1b2lGbpz15ySiTL4lhY',
    appId: '1:191712225769:ios:b3c578abd58cb36b518378',
    messagingSenderId: '191712225769',
    projectId: 'fooddelivery-8eb93',
    storageBucket: 'fooddelivery-8eb93.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIQBUZbwVO-CVa1b2lGbpz15ySiTL4lhY',
    appId: '1:191712225769:ios:84b9ab2b8df17b1e518378',
    messagingSenderId: '191712225769',
    projectId: 'fooddelivery-8eb93',
    storageBucket: 'fooddelivery-8eb93.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApplication.RunnerTests',
  );
}
